DEFINE
	MEASURE 'Key Measures'[Operator Efficiency] = DIVIDE(
			[Total Downtime],
			COUNT(dLine_productivity[Batch])
		)
// (Total Downtime for Operator) / (Number of Batches Managed)                     


EVALUATE
	SUMMARIZECOLUMNS(
		"Total Downtime", [Operator Efficiency]
	)