table dLine_productivity
	lineageTag: f0a1575d-c59f-461c-b700-b975a7b33fe3

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cd72d5be-40d7-4acd-9e3b-b5085b85248d
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Product
		dataType: string
		lineageTag: 6b6e8d6a-20c1-49a3-b6a8-4e0204e4d690
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Batch
		dataType: string
		lineageTag: 9a5762b0-dca8-4954-a0bb-1d18be036b8f
		summarizeBy: none
		sourceColumn: Batch

		annotation SummarizationSetBy = Automatic

	column Operator
		dataType: string
		lineageTag: cdac5902-795d-4768-877a-bdbd8b3a7e22
		summarizeBy: none
		sourceColumn: Operator

		annotation SummarizationSetBy = Automatic

	column 'Start Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: a7aa728b-2dfc-4ffa-a6b2-b2d71a0e6fa8
		summarizeBy: none
		sourceColumn: Start Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'End Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 81e20047-378b-45d1-8370-ccb3bc1bea9c
		summarizeBy: none
		sourceColumn: End Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition dLine_productivity = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\saad\Downloads\Manufacturing Downtime\Manufacturing_Line_Productivity.xlsx"), null, true),
				    #"Line productivity_Sheet" = Source{[Item="Line productivity",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Line productivity_Sheet", [PromoteAllScalars=true]),
				    #"Removed Other Columns" = Table.SelectColumns(#"Promoted Headers",{"Date", "Product", "Batch", "Operator", "Start Time", "End Time"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Date", type date}, {"Product", type text}, {"Batch", type text}, {"Operator", type text}, {"Start Time", type time}, {"End Time", type time}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

