table 'Key Measures'
	lineageTag: 9e52f202-ed14-4c05-acfe-cb9118c1b66b

	measure 'Total Downtime' = SUM(fLine_downtime[Downtime(min)])
		formatString: 0
		lineageTag: c081e0a6-d8b1-4d07-ba9a-64123f50f18c

	measure 'Percentage of Downtime due to Operator Error' =
			
			DIVIDE(CALCULATE(SUM(fLine_downtime[Downtime(min)]),'dDowntime_factors'[Operator Error] ="Yes"),[Total Downtime])
		lineageTag: 77a8424e-5754-4560-8bc6-5edd34c019fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Deviation from Minimum Batch Time' = ```
			
						CALCULATE(
							AVERAGEX(dLine_productivity,SUMX(dLine_productivity,dLine_productivity[Total Time] - RELATED(dProducts[Min batch time])))
						)
			```
		formatString: 0
		lineageTag: 1ebaa9c8-0eae-46fc-9fff-f3c3b7e1c56b

	measure 'Percentage of Batches Exceeding Minimum Time' = ```
			
					DIVIDE(
						CALCULATE(
							COUNT(dLine_productivity[Batch]),
							FILTER(dLine_productivity,'dLine_productivity'[Total Time] = RELATED(dProducts[Min batch time]))
						),
						COUNT(dLine_productivity[Batch])
					)
			```
		lineageTag: e90126e3-b8ff-4595-8ae2-42dc3f3a3b9e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		isHidden
		formatString: 0
		lineageTag: e644e908-5839-435c-98d6-40a5b8b54061
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'Key Measures' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 5695739805894c5c898582c55df815f5

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

