table 'Line productivity'
	lineageTag: f0a1575d-c59f-461c-b700-b975a7b33fe3

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cd72d5be-40d7-4acd-9e3b-b5085b85248d
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: b6d948cd-a9a5-4a94-a567-59ba773dce11
			defaultHierarchy: LocalDateTable_0dce9b95-cc04-4b76-8451-9ec80e763688.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Product
		dataType: string
		lineageTag: 6b6e8d6a-20c1-49a3-b6a8-4e0204e4d690
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Batch
		dataType: int64
		formatString: 0
		lineageTag: 9a5762b0-dca8-4954-a0bb-1d18be036b8f
		summarizeBy: none
		sourceColumn: Batch

		annotation SummarizationSetBy = Automatic

	column Operator
		dataType: string
		lineageTag: cdac5902-795d-4768-877a-bdbd8b3a7e22
		summarizeBy: none
		sourceColumn: Operator

		annotation SummarizationSetBy = Automatic

	column 'Start Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: a7aa728b-2dfc-4ffa-a6b2-b2d71a0e6fa8
		summarizeBy: none
		sourceColumn: Start Time

		variation Variation
			isDefault
			relationship: 67e9e51a-8427-48a5-adc5-81af94cfe506
			defaultHierarchy: LocalDateTable_0d8812f0-89f8-42df-94f9-c9e2357afd08.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'End Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 81e20047-378b-45d1-8370-ccb3bc1bea9c
		summarizeBy: none
		sourceColumn: End Time

		variation Variation
			isDefault
			relationship: 8434d7ed-9462-4a0d-ba9a-01d9ec821140
			defaultHierarchy: LocalDateTable_92a3e330-e684-4c09-bd79-578707129a9c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: a618ad1c-085d-4414-89ec-cab5b05db0e2
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	partition 'Line productivity' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\saad\Downloads\Manufacturing Downtime\Manufacturing_Line_Productivity.xlsx"), null, true),
				    #"Line productivity_Sheet" = Source{[Item="Line productivity",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Line productivity_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Product", type text}, {"Batch", Int64.Type}, {"Operator", type text}, {"Start Time", type datetime}, {"End Time", type datetime}, {"Column7", type any}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

